# Author : amousset <contact@amousset.me>
# See modus_operandi

inherits = "modus_operandi"

"comment" = "red-faint"

"ui.cursor.primary.normal" = { fg = "bg-main", bg = "red" }

[palette]
# Basic values
bg-main = "#fbf7f0"
bg-dim = "#efe9dd"
bg-active = "#c9b9b0"
bg-inactive = "#dfd5cf"
border = "#9f9690"

# Common accent backgrounds
bg-red-nuanced = "#ffe8f0"
bg-green-nuanced = "#e0f5e0"
bg-yellow-nuanced = "#f9ead0"
bg-blue-nuanced = "#ebebff"
bg-magenta-nuanced = "#f6e7ff"
bg-cyan-nuanced = "#e1f3fc"

# Special purpose
bg-completion = "#f0c1cf"
bg-hl-line = "#f1d5d0"
bg-paren-match = "#7fdfcf"
bg-region = "#c2bcb5"

bg-mode-line-active = "#cab9b2"
fg-mode-line-active = "#000000"
border-mode-line-active = "#545454"
bg-mode-line-inactive = "#dfd9cf"
fg-mode-line-inactive = "#585858"
border-mode-line-inactive = "#a59a94"

bg-tab-bar = "#e0d4ce"
bg-tab-current = "#fbf7f0"
bg-tab-other = "#c8b8b2"

# Diffs
bg-added = "#c1f2d1"
bg-added-faint = "#dcf9d1"
bg-added-refine = "#acd6a5"
bg-added-intense = "#8cca8c"
fg-added = "#005000"
fg-added-intense = "#006700"

bg-changed = "#ffdfa9"
bg-changed-faint = "#ffefbf"
bg-changed-refine = "#fac090"
bg-changed-intense = "#d7c20a"
fg-changed = "#553d00"
fg-changed-intense = "#655000"

bg-removed = "#ffd8d5"
bg-removed-faint = "#ffe9e9"
bg-removed-refine = "#f3b5af"
bg-removed-intense = "#d84a4f"
fg-removed = "#8f1313"
fg-removed-intense = "#aa2222"
